# Generated by Django 5.1.4 on 2025-01-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='execution_time',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
