# Generated by Django 5.1.4 on 2025-01-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_testcase_execution_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='execution_time',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
